-- MySQL Script generated by MySQL Workbench
-- Wed Jan 17 15:32:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`klanten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`klanten` (
  `klantid` INT NOT NULL,
  `naam` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `wachtwoord` VARCHAR(45) NULL,
  `adres` VARCHAR(255) NULL,
  `rijbewijsnummer` VARCHAR(45) NULL,
  `telefoonnummer` VARCHAR(45) NULL,
  PRIMARY KEY (`klantid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autos` (
  `autoid` INT NOT NULL,
  `merk` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `jaar` INT NULL,
  `kenteken` VARCHAR(45) NULL,
  `beschikbaarheid` TINYINT NULL,
  PRIMARY KEY (`autoid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`verhuringen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`verhuringen` (
  `verhuurid` INT NOT NULL,
  `verhuurdatum` DATE NULL,
  `huurperiode-tot` DATE NULL,
  `kosten` FLOAT NULL,
  `autos_autoid` INT NOT NULL,
  `klanten_klantid` INT NOT NULL,
  PRIMARY KEY (`verhuurid`),
  INDEX `fk_verhuringen_autos_idx` (`autos_autoid` ASC) VISIBLE,
  INDEX `fk_verhuringen_klanten1_idx` (`klanten_klantid` ASC) VISIBLE,
  CONSTRAINT `fk_verhuringen_autos`
    FOREIGN KEY (`autos_autoid`)
    REFERENCES `mydb`.`autos` (`autoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_verhuringen_klanten1`
    FOREIGN KEY (`klanten_klantid`)
    REFERENCES `mydb`.`klanten` (`klantid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
